export const employees = [
  {
    id: '1',
    name: 'John Doe',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '2',
    name: 'Jane Doe',
    designation: 'HR Manager',
    department: 'HR',
  },
  {
    id: '3',
    name: 'Alice',
    designation: 'Tester',
    department: 'IT',
  },
  {
    id: '4',
    name: 'Bob',
    designation: 'IT Manager',
    department: 'IT',
  },
  {
    id: '5',
    name: 'Charlie',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '6',
    name: 'David',
    designation: 'CEO',
    department: 'IT',
  },
  {
    id: '7',
    name: 'Eve',
    designation: 'Recruiter',
    department: 'IT',
  },
  {
    id: '8',
    name: 'Frank',
    designation: 'Jr.Software Engineer',
    department: 'IT',
  },
  {
    id: '9',
    name: 'Grace',
    designation: 'Sr.Software Engineer',
    department: 'IT',
  },
  {
    id: '10',
    name: 'Hank',
    designation: 'Project Manager',
    department: 'IT',
  },
  {
    id: '11',
    name: 'Ivy',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '12',
    name: 'Jack',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '13',
    name: 'Kelly',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '14',
    name: 'Liam',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '15',
    name: 'Mia',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '16',
    name: 'Nora',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '17',
    name: 'Oliver',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '18',
    name: 'Penny',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '19',
    name: 'Quinn',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '20',
    name: 'Riley',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '21',
    name: 'Sara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '22',
    name: 'Tom',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '23',
    name: 'Uma',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '24',
    name: 'Vera',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '25',
    name: 'Will',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '26',
    name: 'Xavier',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '27',
    name: 'Yara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '28',
    name: 'Zara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '29',
    name: 'Ava',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '30',
    name: 'Ben',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '31',
    name: 'Cody',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '32',
    name: 'Daisy',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '33',
    name: 'Ella',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '34',
    name: 'Fiona',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '35',
    name: 'Gina',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '36',
    name: 'Hugo',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '37',
    name: 'Iris',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '38',
    name: 'Jenny',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '39',
    name: 'Kane',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '40',
    name: 'Lara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '41',
    name: 'Milo',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '42',
    name: 'Nina',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '43',
    name: 'Owen',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '44',
    name: 'Pia',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '45',
    name: 'Quinn',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '46',
    name: 'Rita',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '47',
    name: 'Sam',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '48',
    name: 'Tina',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '49',
    name: 'Uma',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '50',
    name: 'Vera',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '51',
    name: 'Will',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '52',
    name: 'Xena',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '53',
    name: 'Yara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '54',
    name: 'Zara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '55',
    name: 'Ava',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '56',
    name: 'Ben',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '57',
    name: 'Cody',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '58',
    name: 'Daisy',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '59',
    name: 'Ella',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '60',
    name: 'Fiona',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '61',
    name: 'Gina',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '62',
    name: 'Hugo',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '63',
    name: 'Iris',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '64',
    name: 'Jenny',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '65',
    name: 'Kane',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '66',
    name: 'Lara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '67',
    name: 'Milo',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '68',
    name: 'Nina',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '69',
    name: 'Owen',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '70',
    name: 'Pia',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '71',
    name: 'Quinn',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '72',
    name: 'Rita',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '73',
    name: 'Sam',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '74',
    name: 'Tina',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '75',
    name: 'Uma',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '76',
    name: 'Vera',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '77',
    name: 'Will',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '78',
    name: 'Xena',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '79',
    name: 'Yara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '80',
    name: 'Zara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '81',
    name: 'Ava',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '82',
    name: 'Ben',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '83',
    name: 'Cody',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '84',
    name: 'Daisy',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '85',
    name: 'Ella',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '86',
    name: 'Fiona',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '87',
    name: 'Gina',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '88',
    name: 'Hugo',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '89',
    name: 'Iris',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '90',
    name: 'Jenny',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '91',
    name: 'Kane',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '92',
    name: 'Lara',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '93',
    name: 'Milo',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '94',
    name: 'Nina',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '95',
    name: 'Owen',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '96',
    name: 'Pia',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '97',
    name: 'Quinn',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '98',
    name: 'Rita',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '99',
    name: 'Sam',
    designation: 'Software Engineer',
    department: 'IT',
  },
  {
    id: '100',
    name: 'Tina',
    designation: 'Software Engineer',
    department: 'IT',
  },
];
